// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssdskgjvwmasnpnriyuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzZHNrZ2p2d21hc25wbnJpeXV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNzc2MjIsImV4cCI6MjA4ODc1MzYyMn0.XEOmWq-_rBUwmhhLYMcK7l8rU4Tuwn6jONuEqQLyCiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);